#!/usr/bin/env bash
#
# Competitor Intelligence Dashboard — Template Setup Script
#
# Usage:
#   1. Copy setup.example.json → setup.json
#   2. Edit setup.json with your company details & competitors
#   3. Run: bash setup.sh
#
# This script reads setup.json and patches all source files with your
# company name, competitors, keywords, and deployment config.
#
set -euo pipefail

CONFIG="setup.json"

if [ ! -f "$CONFIG" ]; then
  echo "❌ $CONFIG not found. Copy setup.example.json → setup.json and edit it first."
  exit 1
fi

# Check for jq
if ! command -v jq &>/dev/null; then
  echo "❌ jq is required. Install: brew install jq (macOS) or apt install jq (Linux)"
  exit 1
fi

echo "🔧 Reading $CONFIG..."

# ── Extract values ──
COMPANY_ID=$(jq -r '.company.id' "$CONFIG")
COMPANY_NAME=$(jq -r '.company.name' "$CONFIG")
COMPANY_SUBTITLE=$(jq -r '.company.subtitle' "$CONFIG")
COMPANY_WEBSITE=$(jq -r '.company.website' "$CONFIG")
CONTACT_EMAIL=$(jq -r '.company.contact_email' "$CONFIG")
INDUSTRY=$(jq -r '.company.industry' "$CONFIG")
AI_CONTEXT=$(jq -r '.company.ai_context' "$CONFIG")
DASHBOARD_URL=$(jq -r '.deploy.dashboard_url' "$CONFIG")
SITE_NAME=$(jq -r '.deploy.netlify_site_name' "$CONFIG")

USER_AGENT="$COMPANY_NAME Competitor Intel $CONTACT_EMAIL"

echo "   Company:   $COMPANY_NAME ($COMPANY_ID)"
echo "   Email:     $CONTACT_EMAIL"
echo "   Dashboard: $DASHBOARD_URL"
echo ""

# ── 1. Generate src/config/competitors.ts ──
echo "📝 Generating src/config/competitors.ts..."

# Build SELF entity
SELF_QUERIES=$(jq -c '.search_queries' "$CONFIG")

# Build COMPETITORS array
COMPETITORS_TS=""
COMP_COUNT=$(jq '.competitors | length' "$CONFIG")
for i in $(seq 0 $(($COMP_COUNT - 1))); do
  CID=$(jq -r ".competitors[$i].id" "$CONFIG")
  CNAME=$(jq -r ".competitors[$i].name" "$CONFIG")
  CWEB=$(jq -r ".competitors[$i].website" "$CONFIG")
  CQ=$(jq -c ".competitors[$i].search_queries" "$CONFIG")
  QUERIES_TS=""
  QC=$(jq ".competitors[$i].search_queries | length" "$CONFIG")
  for q in $(seq 0 $(($QC - 1))); do
    QV=$(jq -r ".competitors[$i].search_queries[$q]" "$CONFIG")
    QUERIES_TS="$QUERIES_TS    '$QV',
"
  done
  COMPETITORS_TS="$COMPETITORS_TS  {
    id: '$CID',
    name: '$CNAME',
    tier: 'competitor' as const,
    searchQueries: [
$QUERIES_TS    ],
    website: '$CWEB',
  },
"
done

# Build PRIORITY_KEYWORDS
PRIORITY_KW=$(jq -r '.priority_keywords | map("  \u0027" + . + "\u0027") | join(",\n")' "$CONFIG")

# Build PREDICTION_KEYWORDS
PREDICTION_KW=$(jq -r '.prediction_keywords | map("  \u0027" + . + "\u0027") | join(",\n")' "$CONFIG")

# Build SEC_KEYWORD_CATEGORIES
SEC_CRITICAL=$(jq -r '.sec_keyword_categories.critical | map("\u0027" + . + "\u0027") | join(", ")' "$CONFIG")
SEC_WARNING=$(jq -r '.sec_keyword_categories.warning | map("\u0027" + . + "\u0027") | join(", ")' "$CONFIG")
SEC_MONITOR=$(jq -r '.sec_keyword_categories.monitor | map("\u0027" + . + "\u0027") | join(", ")' "$CONFIG")

# Build SEED_AUM_DATA
SEED_AUM_TS=""
SEED_COUNT=$(jq '.seed_aum_data | length' "$CONFIG")
for i in $(seq 0 $(($SEED_COUNT - 1))); do
  SA_NAME=$(jq -r ".seed_aum_data[$i].entity_name" "$CONFIG")
  SA_AUM=$(jq -r ".seed_aum_data[$i].aum_billions" "$CONFIG")
  SA_CAT=$(jq -r ".seed_aum_data[$i].category" "$CONFIG")
  SA_YEAR=$(jq -r ".seed_aum_data[$i].year" "$CONFIG")
  SEED_AUM_TS="$SEED_AUM_TS  { entity_name: '$SA_NAME', aum_billions: $SA_AUM, category: '$SA_CAT', year: $SA_YEAR, source: 'Seed Data', asset_classes: {} },
"
done

# Build FINANCIAL_NEWS_SOURCES
FIN_SOURCES_TS=""
FIN_COUNT=$(jq '.financial_news_sources | length' "$CONFIG")
for i in $(seq 0 $(($FIN_COUNT - 1))); do
  FN_NAME=$(jq -r ".financial_news_sources[$i].name" "$CONFIG")
  FN_URL=$(jq -r ".financial_news_sources[$i].url" "$CONFIG")
  FN_RSS=$(jq -r ".financial_news_sources[$i].rss" "$CONFIG")
  FIN_SOURCES_TS="$FIN_SOURCES_TS  { name: '$FN_NAME', url: '$FN_URL', rss: '$FN_RSS' },
"
done

# Build SELF search queries TS
SELF_QUERIES_TS=""
SQ_COUNT=$(jq '.search_queries | length' "$CONFIG")
for i in $(seq 0 $(($SQ_COUNT - 1))); do
  SQ=$(jq -r ".search_queries[$i]" "$CONFIG")
  SELF_QUERIES_TS="$SELF_QUERIES_TS    '$SQ',
"
done

# Write the competitors.ts file (keeping the type definitions intact)
# We only replace the data exports section. Read existing type defs:
TYPE_DEFS=$(sed -n '1,/^\/\/ ── Data Exports/p' src/config/competitors.ts 2>/dev/null || true)

# If the marker doesn't exist, we'll write the full file
cat > src/config/competitors.ts.new << TSEOF
// ══════════════════════════════════════════════════════════════
// Competitor Intelligence Dashboard — Entity Configuration
// Generated by setup.sh from setup.json
// ══════════════════════════════════════════════════════════════

// ── Types ────────────────────────────────────────────────────

export interface Entity {
  id: string;
  name: string;
  tier: 'self' | 'competitor';
  searchQueries: string[];
  website?: string;
  stocktwits_symbol?: string;
}

export interface Article {
  id: string;
  entity_id: string;
  entity_name: string;
  title: string;
  link: string;
  source_name: string;
  source_domain: string;
  pub_date: string;
  snippet: string;
  sentiment_score: number;
  sentiment_label: 'positive' | 'negative' | 'neutral';
  priority: boolean;
  ai_summary?: string;
  keywords?: string[];
}

export interface FinancialArticle {
  id: string;
  title: string;
  link: string;
  source_name: string;
  source_domain: string;
  pub_date: string;
  snippet: string;
  sentiment_score: number;
  sentiment_label: 'positive' | 'negative' | 'neutral';
}

export interface FinancialNewsSource {
  name: string;
  url: string;
  rss: string;
}

export interface GovEvent {
  id: string;
  title: string;
  agency: string;
  event_date: string;
  event_time: string | null;
  source: string;
  category: string;
  link: string;
  created_at: string;
}

export interface CrawlLogEntry {
  crawl_type: string;
  entity_id: string | null;
  articles_found: number;
  status: string;
  error_message: string | null;
  started_at: string;
  finished_at: string;
}

export interface PredictionMarket {
  id: string;
  platform: string;
  title: string;
  url: string;
  probability: number;
  prev_probability: number | null;
  volume: number | null;
  category: string;
  last_updated: string;
}

export interface SecFiling {
  id: string;
  entity_id: string;
  entity_name: string;
  company_name: string;
  filing_type: string;
  filed_date: string;
  accession_number: string;
  description: string;
  link: string;
  risk_score: number;
  risk_level: 'critical' | 'warning' | 'monitor' | 'info';
  matched_keywords: string[];
  sic_code?: string;
  sic_description?: string;
  keywords?: Array<{ word: string; count: number }>;
}

export interface PersonnelChange {
  id: string;
  entity_id: string;
  entity_name: string;
  person_name: string;
  change_type: 'hire' | 'departure' | 'promotion' | 'board_change';
  old_role: string;
  new_role: string;
  source: string;
  date: string;
  link: string;
}

export interface JobTrend {
  id: string;
  entity_id: string;
  entity_name: string;
  title: string;
  location: string;
  department: string;
  source: string;
  link: string;
  date: string;
}

export interface TrendSnapshot {
  id: string;
  date: string;
  entity_id: string;
  entity_name: string;
  metric_type: string;
  value: number;
}

export interface AumEntry {
  entity_name: string;
  aum_billions: number;
  category: string;
  source: string;
  year: number;
  asset_classes: Record<string, number>;
}

export interface FinraAlert {
  id: string;
  firm_name: string;
  firm_crd: string;
  action_type: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  summary: string;
  date: string;
  link: string;
}

export interface FormAdvAnalysis {
  entity_id: string;
  entity_name: string;
  crd_number: string;
  registration_status: string;
  aum_regulatory: number | null;
  employee_count: number | null;
  has_disclosures: boolean;
  disclosure_count: number;
  branches_count: number;
  last_updated: string;
  sec_link: string;
}

export interface Holdings13F {
  entity_id: string;
  entity_name: string;
  cik: string;
  filing_date: string;
  report_date: string;
  total_value: number;
  holdings_count: number;
  top_holdings: Array<{
    name: string;
    cusip: string;
    value: number;
    shares: number;
    pct_of_total: number;
  }>;
  link: string;
}

export interface SocialMention {
  id: string;
  entity_id: string;
  entity_name: string;
  platform: string;
  author: string;
  content: string;
  url: string;
  score: number;
  sentiment_score: number;
  sentiment_label: 'positive' | 'negative' | 'neutral';
  created_at: string;
}

export interface DailyBrief {
  generated_at: string;
  market_sentiment: {
    avg_score: number;
    trend: string;
    positive_pct: number;
    neutral_pct: number;
    negative_pct: number;
    total_articles: number;
    prev_avg_score: number;
  };
  top_stories: Array<{
    title: string;
    link: string;
    entity_name: string;
    sentiment_score: number;
    sentiment_label: string;
    pub_date: string;
    reason: string;
  }>;
  risk_alerts: SecFiling[];
  prediction_movers: Array<{
    title: string;
    probability: number;
    change: number;
    url: string;
    platform: string;
  }>;
  upcoming_events: GovEvent[];
  competitor_activity: Array<{
    entity_id: string;
    entity_name: string;
    article_count: number;
    top_headline: string;
    top_link: string;
  }>;
  key_themes: Array<{ theme: string; count: number }>;
  personnel_moves: Array<{
    person_name: string;
    entity_name: string;
    change_type: string;
    old_role: string;
    new_role: string;
    date: string;
  }>;
  finra_alerts: FinraAlert[];
  hiring_signals: Array<{
    entity_name: string;
    count: number;
    top_dept: string;
  }>;
  market_indicators: Record<string, any>;
  total_aum_billions: number | null;
  aum_leaderboard: AumEntry[];
}

// ── Data Exports ─────────────────────────────────────────

export const SELF: Entity = {
  id: '${COMPANY_ID}',
  name: '${COMPANY_NAME}',
  tier: 'self',
  searchQueries: [
${SELF_QUERIES_TS}  ],
  website: '${COMPANY_WEBSITE}',
};

export const COMPETITORS: Entity[] = [
${COMPETITORS_TS}];

export const ALL_ENTITIES: Entity[] = [SELF, ...COMPETITORS];

export const PRIORITY_KEYWORDS: string[] = [
${PRIORITY_KW},
];

export const SEC_KEYWORD_CATEGORIES: Record<string, { keywords: string[]; severity: number }> = {
  critical: { keywords: [${SEC_CRITICAL}], severity: 3 },
  warning:  { keywords: [${SEC_WARNING}], severity: 2 },
  monitor:  { keywords: [${SEC_MONITOR}], severity: 1 },
};

export const FILING_TYPE_INFO: Record<string, string> = {
  'ADV': 'Investment Adviser Registration',
  '10-K': 'Annual Report',
  '10-Q': 'Quarterly Report',
  '13F': 'Institutional Holdings',
  'S-1': 'IPO Registration',
  '8-K': 'Current Report (Material Event)',
  'DEF 14A': 'Proxy Statement',
  'SC 13D': 'Beneficial Ownership (>5%)',
  'SC 13G': 'Passive Beneficial Ownership',
};

export const SIC_DESCRIPTIONS: Record<string, string> = {
  '6020': 'Savings Institutions, Federally Chartered',
  '6022': 'State-Chartered Savings Institutions',
  '6035': 'Savings Institution, Federally Chartered',
  '6036': 'Savings Institutions, Not Federally Chartered',
  '6141': 'Personal Credit Institutions',
  '6153': 'Short-Term Business Credit',
  '6159': 'Federal-Sponsored Credit Agencies',
  '6199': 'Finance Services',
  '6200': 'Security & Commodity Services',
  '6211': 'Security Brokers & Dealers',
  '6282': 'Investment Advice',
  '6311': 'Fire, Marine & Casualty Insurance',
  '6321': 'Accident and Health Insurance',
  '6324': 'Hospital & Medical Service Plans',
  '6331': 'Fire, Marine & Casualty Insurance',
  '6411': 'Insurance Agents, Brokers',
  '6500': 'Real Estate',
  '6512': 'Operators of Apartment Buildings',
  '6552': 'Subdividers & Developers',
  '6726': 'Investment Offices, NEC',
  '6770': 'Blank Checks',
};

export const PREDICTION_KEYWORDS: string[] = [
${PREDICTION_KW},
];

export const SEED_AUM_DATA: AumEntry[] = [
${SEED_AUM_TS}];

export const FINANCIAL_NEWS_SOURCES: FinancialNewsSource[] = [
${FIN_SOURCES_TS}];
TSEOF

mv src/config/competitors.ts.new src/config/competitors.ts
echo "   ✅ src/config/competitors.ts"

# ── 2. Patch HTML files ──
echo "📝 Patching HTML files..."

# index.html — title
sed -i '' "s|<title>Competitor Intelligence.*</title>|<title>Competitor Intelligence | ${COMPANY_NAME}</title>|" public/index.html

# index.html — subtitle
sed -i '' "s|<span class=\"subtitle\">.*</span>|<span class=\"subtitle\">${COMPANY_SUBTITLE}</span>|" public/index.html

# index.html — self entity option
sed -i '' "s|<option value=\"[^\"]*\">.*Self.*</option>|<option value=\"${COMPANY_ID}\">${COMPANY_NAME} (Self)</option>|" public/index.html

# login.html — subtitle
sed -i '' "s|<span class=\"subtitle\">.*</span>|<span class=\"subtitle\">${COMPANY_SUBTITLE}</span>|" public/login.html

echo "   ✅ public/index.html"
echo "   ✅ public/login.html"

# ── 3. Patch USER_AGENT strings in crawlers ──
echo "📝 Patching USER_AGENT strings..."

for f in \
  src/crawlers/secScanner.ts \
  src/crawlers/aumCrawler.ts \
  src/crawlers/personnelCrawler.ts \
  src/crawlers/discoverer.ts \
  src/crawlers/socialCrawler.ts \
  src/services/aiSummarizer.ts \
; do
  if [ -f "$f" ]; then
    sed -i '' "s|const USER_AGENT = '.*';|const USER_AGENT = '${USER_AGENT}';|" "$f"
    echo "   ✅ $f"
  fi
done

# ── 4. Patch email templates ──
echo "📝 Patching email templates..."

for f in src/services/emailAlert.ts src/services/resendEmail.ts; do
  if [ -f "$f" ]; then
    # Replace company name references
    sed -i '' "s|The Dobbs Group|${COMPANY_NAME}|g" "$f"
    sed -i '' "s|Graystone Consulting|${COMPANY_SUBTITLE##*| }|g" "$f"
    sed -i '' "s|https://competitor-intel-dashboard.netlify.app|${DASHBOARD_URL}|g" "$f"
    echo "   ✅ $f"
  fi
done

# ── 5. Patch AI summarizer context ──
echo "📝 Patching AI summarizer..."
if [ -f "src/services/aiSummarizer.ts" ]; then
  # Replace the AI context line
  sed -i '' "s|You are an analyst at an institutional investment consulting firm.*\.|${AI_CONTEXT}|" src/services/aiSummarizer.ts
  echo "   ✅ src/services/aiSummarizer.ts"
fi

# ── 6. Patch briefGenerator.ts ──
echo "📝 Patching brief generator..."
if [ -f "src/services/briefGenerator.ts" ]; then
  sed -i '' "s|entity_id === 'dobbs-group'|entity_id === '${COMPANY_ID}'|g" src/services/briefGenerator.ts
  echo "   ✅ src/services/briefGenerator.ts"
fi

# ── 7. Patch app.js — self entity ID references ──
echo "📝 Patching app.js..."
sed -i '' "s|'dobbs-group'|'${COMPANY_ID}'|g" public/app.js
echo "   ✅ public/app.js"

echo ""
echo "═══════════════════════════════════════════════════"
echo "  ✅ Setup complete!"
echo "═══════════════════════════════════════════════════"
echo ""
echo "  Company:     ${COMPANY_NAME}"
echo "  Self ID:     ${COMPANY_ID}"
echo "  Competitors: ${COMP_COUNT}"
echo ""
echo "  Next steps:"
echo "  1. Set your auth secret:  netlify env:set AUTH_SECRET <your-secret>"
echo "  2. (Optional) Set email:  netlify env:set RESEND_API_KEY <key>"
echo "  3. Deploy:                netlify deploy --prod --dir=."
echo "  4. Open your dashboard:   ${DASHBOARD_URL}"
echo "  5. Login and click 'Crawl Now' to start collecting data!"
echo ""
